### PR TITLE
Hooks:Milestone 4

### PR DESCRIPTION
**Pull request by Tumworobere**
In this milestone, I achieved the following

- Refactored the Calculator component (components/Calculator.js) from a class-based component to a functional component with hooks.

### CODE REVIEW

**Comment by arslanbisharat** [comment]
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [ ] Remove node modules from your project directory.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Tumworobere** [comment]
> # Changes Requested,
> 
> Hi there,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> ## Required Changes ♻️
> 
>     * [ ]  Remove node modules from your project directory.
> 
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thanks, @arslanbisharat  for the review. But I don't have node modules in my project. Could you be getting something different from your side?

**Comment by Tumworobere** [comment]
> > # Changes Requested,
> > Hi there,
> > Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> > ## Required Changes ♻️
> > ```
> > * [ ]  Remove node modules from your project directory.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Cheers and Happy coding!👏👏👏
> > Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> > _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
> 
> Thanks, @arslanbisharat for the review. But I don't have node modules in my project. Could you be getting something different from your side?

hooks

**Comment by arslanbisharat** [comment]
My apologizes. I did make a mistake while reviewing your project. 

Please submit your project and the next CR will approve it.

**Comment by Tumworobere** [comment]
> My apologizes. I did make a mistake while reviewing your project.
> 
> Please submit your project and the next CR will approve it.

It is well @arslanbisharat .Let me resubmit now

**Review by ZeenatLawal — APPROVED** [review]
Hi @Tumworobere, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 
6vEo


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Tumworobere** [comment]
> Hi @Tumworobere,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
> ## Congratulations! 🎉
> 
> 6vEo
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you @ZeenatLawal

**Pull request merged**
