### PR TITLE
Components UI :Milestone 2

### PR DESCRIPTION
**Pull request by Tumworobere**
In this milestone I acheived the following

- Deleted all the boilerplate from CRA (text, images, styles).
- Created a directory called components.
- Created a new Calculator.js file.
- Use class based components.

### CODE REVIEW

**Review by elyor-doniyorov — COMMENTED** [review]
Hi @Tumworobere, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a `node_modules` folder not in the .`gitignore `file in the default branch. In your `dev` branch kindly put the `node modules` folder in `.gitignore` because this is causing loading issues.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @Tumworobere,** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- Please add the `operate.js`, and also make sure the calculator works.

jjj


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N./A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Tumworobere** [comment]
> ### **Hi @Tumworobere,**
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> ## Required Changes ♻️
> 
> _Check the comments under the review._
> 
>     * Please add the `operate.js`, and also make sure the calculator works.
> 
> 
> jjj
> ## Optional suggestions
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> You can also consider:
> 
>     * N./A
> 
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thanks for the review @dasileker  however I thought am supposed to add these required changes in my next project.
Kindly advise if am wrong on this.Thanks!

**Comment by dasileker** [comment]
> > ### **Hi @Tumworobere,**
> > 
> > Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> > ## Required Changes ♻️
> > 
> > _Check the comments under the review._
> > 
> >     * Please add the `operate.js`, and also make sure the calculator works.
> > 
> > 
> > jjj
> > ## Optional suggestions
> > 
> > _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> > 
> > You can also consider:
> > 
> >     * N./A
> > 
> > 
> > Cheers and Happy coding!👏👏👏
> > 
> > Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> > 
> > **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> > 
> > _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
> 
> Thanks for the review @dasileker  however I thought am supposed to add these required changes in my next project.
> Kindly advise if am wrong on this.Thanks!
> 


It's on this milestone. The operate.js and calculator.js should be in this milestone because its an event milestone, the calculator should be relatively working

**Comment by Tumworobere** [comment]
> > > ### **Hi @Tumworobere,**
> > > Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> > > ## Required Changes ♻️
> > > _Check the comments under the review._
> > > ```
> > > * Please add the `operate.js`, and also make sure the calculator works.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > jjj
> > > ## Optional suggestions
> > > _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> > > You can also consider:
> > > ```
> > > * N./A
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Cheers and Happy coding!👏👏👏
> > > Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> > > **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> > > _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
> > 
> > 
> > Thanks for the review @dasileker  however I thought am supposed to add these required changes in my next project.
> > Kindly advise if am wrong on this.Thanks!
> 
> It's on this milestone. The operate.js and calculator.js should be in this milestone because its an event milestone, the calculator should be relatively working

Sorry about this @dasileker  I submitted my PR link to the wrong milestone.It was meant for the components milestone.Am very sorry about this.

**Comment by dasileker** [comment]
Please close this pr and open. The right one and resubmit.

**Comment by Tumworobere** [comment]
> Please close this pr and open. The right one and resubmit.

Thanks @dasileker . I will do that now!

**Review by dasileker — APPROVED** [review]
## **Hi @Tumworobere,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 

### **Optional**

- Please be careful about the **node_modules**, I can see that the push is contained it,  before submitting see the gitignore file.
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
